package ro.mpp.implementation;

public enum RequestType {
    LOGIN,
    GET_USER_BY_ID,
    GET_ALL_USERS,
    ADD_USER,
    DELETE_USER,
    LOGOUT,
    // === MISSION ===
    GET_MISSION_BY_ID,
    GET_ALL_MISSIONS,
    GET_FINISHED_MISSIONS,
    ADD_MISSION,
    DELETE_MISSION,

    // === ASSIGNMENT ===
    GET_MISSIONS_FOR_USER,
    ASSIGN_MISSION_TO_USER,
    UPLOAD_FILE_FOR_ASSIGNMENT,
    VALIDATE_ASSIGNMENT,
    GET_ALL_ASSIGNMENTS,
    GET_UNVALIDATED_ASSIGNMENTS,
    DELETE_ASSIGNMENT,
    ASSIGNEMENTS_FOR_USER
}
